sudo: false

language: php

php:
  - 7.1.0

env:
  - ILLUMINATE_VERSION=5.5.*

matrix:
  include:
    - php: 7.1.0
      env: ILLUMINATE_VERSION=5.5.*
    - php: 7.1.3
      env: ILLUMINATE_VERSION=5.6.*
    - php: 7.1.3
      env: ILLUMINATE_VERSION=5.7.*
    - php: 7.1.3
      env: ILLUMINATE_VERSION=5.8.*
    - php: 7.2.0
      env: ILLUMINATE_VERSION=6.*
before_script:
  - composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update
  - composer require "illuminate/config:${ILLUMINATE_VERSION}" --no-update
  - composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - bash <(curl -s build/logs/ https://codecov.io/bash)
