FROM 959744386191.dkr.ecr.eu-west-1.amazonaws.com/podpoint/php:7.1-dev

COPY . /app/.

WORKDIR /app

RUN apk add openssh-client

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
